//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.ModelBinding;

    public partial class Employee
    {
        public int EmployeeId { get; set; }
        [DisplayName("First name")]
        public string FirstName { get; set; }
        [DisplayName("Last name")]
        public string LastName { get; set; }
      

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}"), DisplayName("Birth date")]
        public System.DateTime BirthDate { get; set; }
        [DisplayName("Manager")]
        public string Manager { get; set; }
        [DisplayName("Department ID")]
        public int DepartmentId { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
